xml_path: "/Users/rahulavasarala/Desktop/OpenSai/WireConnectAgent/models/scenes/fr3peghole_v2.xml"
action_type: "model"

model: #This is if we need it
  run_dir: "/Users/rahulavasarala/Desktop/OpenSai/WireConnectAgent/python_app/runs"
  run_name: "peginhole_yesforce"
  iter: 30

debug: True
replay: True

